// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yuka2Back.Data;

#nullable disable

namespace Yuka2Back.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226173417_AddNewFeatureFlags")]
    partial class AddNewFeatureFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yuka2Back.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Yuka2Back.Models.AnalyticsEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EventType");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("AnalyticsEvents");
                });

            modelBuilder.Entity("Yuka2Back.Models.ApiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Path");

                    b.HasIndex("StatusCode");

                    b.HasIndex("UserId");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("Yuka2Back.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AccountDeletionEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("BiometricAuthEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("FavoritesEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ForceUpdateMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("HistoryEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LatestAppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaintenanceMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("MaintenanceMode")
                        .HasColumnType("bit");

                    b.Property<string>("MinAppVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("OpenFoodFactsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PasswordResetEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("RegistrationEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ScanEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SearchEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("Yuka2Back.Models.AppSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceOS")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AppSessions");
                });

            modelBuilder.Entity("Yuka2Back.Models.FavoriteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("Yuka2Back.Models.PageView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnteredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnteredAt");

                    b.HasIndex("PageName");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("PageViews");
                });

            modelBuilder.Entity("Yuka2Back.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergens")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Calories")
                        .HasColumnType("float");

                    b.Property<double?>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<string>("Categories")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Fat")
                        .HasColumnType("float");

                    b.Property<double?>("Fiber")
                        .HasColumnType("float");

                    b.Property<int?>("HealthScore")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Ingredients")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPalmOilFree")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("NovaGroup")
                        .HasColumnType("int");

                    b.Property<string>("NutriScore")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<double?>("Proteins")
                        .HasColumnType("float");

                    b.Property<string>("Quantity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Salt")
                        .HasColumnType("float");

                    b.Property<double?>("SaturatedFat")
                        .HasColumnType("float");

                    b.Property<double?>("Sugars")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Allergens = "Lait, Soja, Fruits à coque",
                            Barcode = "3017620422003",
                            Brand = "Ferrero",
                            Calories = 539.0,
                            Carbohydrates = 57.5,
                            Categories = "Pâtes à tartiner",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1941),
                            Fat = 30.899999999999999,
                            Fiber = 0.0,
                            HealthScore = 15,
                            Ingredients = "Sucre, huile de palme, noisettes 13%, cacao maigre 7.4%, lait écrémé en poudre 6.6%, lactosérum en poudre, émulsifiants : lécithines (soja), vanilline",
                            IsOrganic = false,
                            IsPalmOilFree = false,
                            IsVegan = false,
                            Name = "Nutella",
                            NovaGroup = 4,
                            NutriScore = "E",
                            Proteins = 6.2999999999999998,
                            Quantity = "400g",
                            Salt = 0.107,
                            SaturatedFat = 10.6,
                            Sugars = 56.299999999999997,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1945)
                        },
                        new
                        {
                            Id = 2,
                            Allergens = "",
                            Barcode = "3175680011480",
                            Brand = "Volvic",
                            Calories = 0.0,
                            Carbohydrates = 0.0,
                            Categories = "Boissons, Eaux",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1959),
                            Fat = 0.0,
                            Fiber = 0.0,
                            HealthScore = 100,
                            Ingredients = "Eau minérale naturelle",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = true,
                            Name = "Eau minérale naturelle",
                            NovaGroup = 1,
                            NutriScore = "A",
                            Proteins = 0.0,
                            Quantity = "1.5L",
                            Salt = 0.0,
                            SaturatedFat = 0.0,
                            Sugars = 0.0,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1959)
                        },
                        new
                        {
                            Id = 3,
                            Allergens = "Lait",
                            Barcode = "3228857000166",
                            Brand = "Président",
                            Calories = 299.0,
                            Carbohydrates = 0.5,
                            Categories = "Fromages",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1963),
                            Fat = 24.0,
                            Fiber = 0.0,
                            HealthScore = 35,
                            Ingredients = "Lait pasteurisé, sel, ferments lactiques, coagulant",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = false,
                            Name = "Camembert",
                            NovaGroup = 3,
                            NutriScore = "D",
                            Proteins = 20.0,
                            Quantity = "250g",
                            Salt = 1.6000000000000001,
                            SaturatedFat = 16.600000000000001,
                            Sugars = 0.5,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1963)
                        },
                        new
                        {
                            Id = 4,
                            Allergens = "",
                            Barcode = "3560070472734",
                            Brand = "Carrefour Bio",
                            Calories = 19.0,
                            Carbohydrates = 1.8,
                            Categories = "Légumes, Salades",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1967),
                            Fat = 0.29999999999999999,
                            Fiber = 1.8,
                            HealthScore = 92,
                            Ingredients = "Salade mêlée issue de l'agriculture biologique",
                            IsOrganic = true,
                            IsPalmOilFree = true,
                            IsVegan = true,
                            Name = "Salade mêlée",
                            NovaGroup = 1,
                            NutriScore = "A",
                            Proteins = 1.5,
                            Quantity = "150g",
                            Salt = 0.02,
                            SaturatedFat = 0.0,
                            Sugars = 0.59999999999999998,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1967)
                        },
                        new
                        {
                            Id = 5,
                            Allergens = "Gluten, Lait, Soja",
                            Barcode = "3017760000109",
                            Brand = "LU",
                            Calories = 468.0,
                            Carbohydrates = 70.0,
                            Categories = "Biscuits, Snacks sucrés",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1970),
                            Fat = 17.0,
                            Fiber = 2.2999999999999998,
                            HealthScore = 22,
                            Ingredients = "Farine de blé 47%, sucre, huiles végétales (palme, colza), cacao maigre en poudre 5.1%, sirop de glucose, amidon de blé, poudre à lever",
                            IsOrganic = false,
                            IsPalmOilFree = false,
                            IsVegan = false,
                            Name = "Prince Chocolat",
                            NovaGroup = 4,
                            NutriScore = "D",
                            Proteins = 6.2000000000000002,
                            Quantity = "300g",
                            Salt = 0.68000000000000005,
                            SaturatedFat = 8.1999999999999993,
                            Sugars = 32.0,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1971)
                        },
                        new
                        {
                            Id = 6,
                            Allergens = "",
                            Barcode = "3274080005003",
                            Brand = "Andros",
                            Calories = 52.0,
                            Carbohydrates = 11.9,
                            Categories = "Compotes, Fruits",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1974),
                            Fat = 0.10000000000000001,
                            Fiber = 1.7,
                            HealthScore = 78,
                            Ingredients = "Pommes 100%",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = true,
                            Name = "Compote Pomme",
                            NovaGroup = 1,
                            NutriScore = "A",
                            Proteins = 0.29999999999999999,
                            Quantity = "750g",
                            Salt = 0.0,
                            SaturatedFat = 0.0,
                            Sugars = 10.699999999999999,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1974)
                        },
                        new
                        {
                            Id = 7,
                            Allergens = "Lait",
                            Barcode = "3256540001305",
                            Brand = "Danone",
                            Calories = 46.0,
                            Carbohydrates = 4.7000000000000002,
                            Categories = "Produits laitiers, Yaourts",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1977),
                            Fat = 1.0,
                            Fiber = 0.0,
                            HealthScore = 85,
                            Ingredients = "Lait écrémé, ferments lactiques",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = false,
                            Name = "Yaourt Nature",
                            NovaGroup = 1,
                            NutriScore = "A",
                            Proteins = 4.2000000000000002,
                            Quantity = "4x125g",
                            Salt = 0.13,
                            SaturatedFat = 0.69999999999999996,
                            Sugars = 4.7000000000000002,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1978)
                        },
                        new
                        {
                            Id = 8,
                            Allergens = "",
                            Barcode = "3560070452712",
                            Brand = "Lay's",
                            Calories = 536.0,
                            Carbohydrates = 50.0,
                            Categories = "Chips, Snacks salés",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1982),
                            Fat = 35.0,
                            Fiber = 4.2999999999999998,
                            HealthScore = 38,
                            Ingredients = "Pommes de terre, huile de tournesol 33%, sel",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = true,
                            Name = "Chips nature",
                            NovaGroup = 3,
                            NutriScore = "C",
                            Proteins = 6.5,
                            Quantity = "150g",
                            Salt = 1.3,
                            SaturatedFat = 3.0,
                            Sugars = 0.5,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1983)
                        },
                        new
                        {
                            Id = 9,
                            Allergens = "",
                            Barcode = "3073781155211",
                            Brand = "Bonduelle",
                            Calories = 57.0,
                            Carbohydrates = 6.4000000000000004,
                            Categories = "Conserves, Légumes",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1986),
                            Fat = 2.2999999999999998,
                            Fiber = 1.6000000000000001,
                            HealthScore = 82,
                            Ingredients = "Tomates 38%, courgettes 21%, poivrons rouges 12%, aubergines 9%, oignons, huile de tournesol, sel, ail, basilic, thym, poivre",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = true,
                            Name = "Ratatouille cuisinée",
                            NovaGroup = 3,
                            NutriScore = "A",
                            Proteins = 1.1000000000000001,
                            Quantity = "660g",
                            Salt = 0.65000000000000002,
                            SaturatedFat = 0.29999999999999999,
                            Sugars = 4.2999999999999998,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1986)
                        },
                        new
                        {
                            Id = 10,
                            Allergens = "Lait, Soja",
                            Barcode = "3046920028363",
                            Brand = "Lindt",
                            Calories = 545.0,
                            Carbohydrates = 33.0,
                            Categories = "Chocolats",
                            CreatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1990),
                            Fat = 41.0,
                            Fiber = 11.0,
                            HealthScore = 55,
                            Ingredients = "Pâte de cacao, sucre, beurre de cacao, vanille",
                            IsOrganic = false,
                            IsPalmOilFree = true,
                            IsVegan = false,
                            Name = "Chocolat noir 70%",
                            NovaGroup = 3,
                            NutriScore = "C",
                            Proteins = 9.3000000000000007,
                            Quantity = "100g",
                            Salt = 0.02,
                            SaturatedFat = 25.0,
                            Sugars = 26.0,
                            UpdatedAt = new DateTime(2026, 2, 26, 17, 34, 17, 383, DateTimeKind.Utc).AddTicks(1990)
                        });
                });

            modelBuilder.Entity("Yuka2Back.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Yuka2Back.Models.ScanHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ScanHistories");
                });

            modelBuilder.Entity("Yuka2Back.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DarkModeEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DietType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DietaryGoals")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalScans")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Yuka2Back.Models.AnalyticsEvent", b =>
                {
                    b.HasOne("Yuka2Back.Models.AppSession", "Session")
                        .WithMany("Events")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Yuka2Back.Models.FavoriteProduct", b =>
                {
                    b.HasOne("Yuka2Back.Models.Product", "Product")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yuka2Back.Models.User", "User")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yuka2Back.Models.PageView", b =>
                {
                    b.HasOne("Yuka2Back.Models.AppSession", "Session")
                        .WithMany("PageViews")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Yuka2Back.Models.RefreshToken", b =>
                {
                    b.HasOne("Yuka2Back.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yuka2Back.Models.ScanHistory", b =>
                {
                    b.HasOne("Yuka2Back.Models.Product", "Product")
                        .WithMany("ScanHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yuka2Back.Models.User", "User")
                        .WithMany("ScanHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yuka2Back.Models.AppSession", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PageViews");
                });

            modelBuilder.Entity("Yuka2Back.Models.Product", b =>
                {
                    b.Navigation("FavoriteProducts");

                    b.Navigation("ScanHistories");
                });

            modelBuilder.Entity("Yuka2Back.Models.User", b =>
                {
                    b.Navigation("FavoriteProducts");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ScanHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
